app = "dgii-api-vt"
primary_region = "mia"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 80
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls"]
    port = 443
